# Use root/example as user/password credentials
# docker reference documentation https://docs.docker.com/reference/
version: '3.1'
name: pm-app

services:

  #db2:
  #  image: mariadb #This pulls version 11.3.2
  #  restart: always
  #  container_name: pm_db_mariadb
  #  environment:
  #    MARIADB_ROOT_PASSWORD: 123
  #  ports:
  #    - 3306:3306
  #  volumes:
  #    - mariadb:/var/lib/mysql

  db:
    image: postgres:13
    restart: always
    container_name: pm_db_postgresql
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    container_name: pm_adminer
    ports:
      - 8080:8080

  #pgloader:
  #  image: dimitri/pgloader:latest
  #  container_name: pm_pgloader

  web_svr:
    #build: .
    image: pm_server:v1
    restart: always
    container_name: pm_web_svr
    #environment:
    #  - DATA_SOURCE="PM_web_svr_app:123@tcp(pm_db:3306)/project_mgnt?parseTime=true"
    #  - SERVER_HOST="web_svr"
    ports:
      - 8280:80
      - 8285:443
    entrypoint:
      - /app/pm_server
      - -host
      - pm_web_svr
      - -porthttps
      - "443"
      - -porthttp
      - "80"
      - -servercert
      - ./certs/app/localhost.crt
      - -serverkey
      - ./certs/app/localhost.key
      - -servercacert
      - ./certs/app/certauth.crt
      - -clientcacert
      - ./certs/app/certauth.crt
      - -certopt
      - "0"
      - -emailtoken
      - ./certs/gmail/client_token.json
      - -emailsecret
      - ./certs/gmail/client_secret.json
      - -emailaddr
      - vincejnz@gmail.com
      #- -logfile
      #- ./pm_server.log
      - -datasource
      #- PM_web_svr_app:123@tcp(pm_db_mariadb:3306)/project_mgnt?parseTime=true&timeout=30s
      # POSTGRES: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
      #- postgres://PM_web_svr_app:123@db:5432/project_mgnt?sslmode=verify-full
      - postgres://pm_web_svr_app:123@db:5432/project_mgnt?sslmode=disable
      #- PM_web_svr_app:123@tcp(pm_db:3306)/project_mgnt?parseTime=true

volumes:
  #mariadb:
  postgresql: