FROM centos:8

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql

RUN dnf update -y
#RUN dnf install mariadb-server

#RUN systemctl start mariadb
#RUN systemctl enable mariadb

VOLUME /var/lib/mysql

EXPOSE 3306
CMD ["mariadbd"]