CREATE TABLE IF NOT EXISTS st_users (
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Username VARCHAR(255) NOT NULL UNIQUE,
  Email VARCHAR(255) NOT NULL UNIQUE,
  User_status_ID INT NOT NULL,
  Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);
