-- Table: public.at_booking_vouchers

CREATE TABLE IF NOT EXISTS public.at_booking_vouchers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    discount_percent numeric(5,2),
    fixed_cost numeric(10,2),
    expiry_date date,
    is_active boolean NOT NULL DEFAULT true,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT at_booking_vouchers_pkey PRIMARY KEY (id),
    CONSTRAINT at_booking_vouchers_code_key UNIQUE (code),
    CONSTRAINT at_booking_vouchers_discount_ck CHECK (discount_percent IS NULL OR (discount_percent >= 0 AND discount_percent <= 100)),
    CONSTRAINT at_booking_vouchers_fixed_cost_ck CHECK (fixed_cost IS NULL OR fixed_cost >= 0),
    CONSTRAINT at_booking_vouchers_mode_ck CHECK ((discount_percent IS NULL) <> (fixed_cost IS NULL))
)

TABLESPACE pg_default;

ALTER TABLE public.at_booking_vouchers
    ADD COLUMN IF NOT EXISTS fixed_cost numeric(10,2);

ALTER TABLE public.at_booking_vouchers
    ADD COLUMN IF NOT EXISTS expiry_date date;

ALTER TABLE public.at_booking_vouchers
    ALTER COLUMN discount_percent DROP NOT NULL;

ALTER TABLE public.at_booking_vouchers
    ALTER COLUMN discount_percent DROP DEFAULT;

ALTER TABLE public.at_booking_vouchers
    DROP CONSTRAINT IF EXISTS at_booking_vouchers_discount_ck;

ALTER TABLE public.at_booking_vouchers
    DROP CONSTRAINT IF EXISTS at_booking_vouchers_fixed_cost_ck;

ALTER TABLE public.at_booking_vouchers
    DROP CONSTRAINT IF EXISTS at_booking_vouchers_mode_ck;

ALTER TABLE public.at_booking_vouchers
    ADD CONSTRAINT at_booking_vouchers_discount_ck CHECK (discount_percent IS NULL OR (discount_percent >= 0 AND discount_percent <= 100));

ALTER TABLE public.at_booking_vouchers
    ADD CONSTRAINT at_booking_vouchers_fixed_cost_ck CHECK (fixed_cost IS NULL OR fixed_cost >= 0);

ALTER TABLE public.at_booking_vouchers
    ADD CONSTRAINT at_booking_vouchers_mode_ck CHECK ((discount_percent IS NULL) <> (fixed_cost IS NULL));

ALTER TABLE IF EXISTS public.at_booking_vouchers
    OWNER to myuser;

GRANT ALL ON TABLE public.at_booking_vouchers TO api_user;
GRANT ALL ON TABLE public.at_booking_vouchers TO myuser;

CREATE TRIGGER update_at_booking_vouchers_modified
    BEFORE UPDATE
    ON public.at_booking_vouchers
    FOR EACH ROW
    EXECUTE FUNCTION public.update_modified_column();

-- Seed examples
INSERT INTO public.at_booking_vouchers (code, discount_percent, fixed_cost, expiry_date, is_active)
VALUES
    ('WELCOME10', 10.00, NULL, NULL, true),
    ('SAVE15', 15.00, NULL, NULL, true),
    ('FLAT50', NULL, 50.00, NULL, true)
ON CONFLICT (code) DO NOTHING;
