CREATE TABLE IF NOT EXISTS st_users (
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Username VARCHAR(255) NOT NULL UNIQUE,
  Email VARCHAR(255) NOT NULL UNIQUE,
  User_status_ID INT NOT NULL DEFAULT 0,  -- Default value set to 0
  Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.Modified = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_st_users_modified
BEFORE UPDATE ON st_users
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();