CREATE TABLE IF NOT EXISTS `st_user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(255) NOT NULL UNIQUE,
  `Email` VARCHAR(255) NOT NULL UNIQUE,
  `User_status_ID` int(11) NOT NULL,
  `Created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;